# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UQBHcn-X3KSgl3yq51ouLll3aquClm2o
"""



import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

df.isnull().sum()

df=df.dropna(axis=0)

dosya_yolu = ('/content/drive/My Drive/Colab Notebooks')   # Veri setinin bulunduğu klasörün yolu

import pandas as pd

# Veri setini okuma
df = pd.read_csv(dosya_yolu + '/trafikKaza.csv')
 # Dosya adını ve uzantısını uygun şekilde güncelleyin

plt.figure(figsize=(10,6))
sns.boxplot(data=df)
plt.title("Aykırı değer analizi")
plt.show()

df.info

mahalle_sutunu=df["MAHALLE"]
kadin_surucu_sutunnu=df["SURUCU CINSIYET"]





plt.figure(figsize=(4, 4))
sns.countplot(x='SURUCU CINSIYET', data=df,color='red')
plt.title('Cinsiyetlere göre Kaza dağılımı')
plt.show()

df.shape

df[df['ARAC MODELI']>90] #araç modeli 90 den yukarıya olanlar

plt.figure(figsize=(10, 4))
sns.countplot(x='KAZA SAAT', data=df)
plt.title('Kaza Saatlerine Göre Kazaların Dağılımı')
plt.show()

temel_istatiskler = df.describe()
print(temel_istatiskler)

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.scatterplot(x='YARALI SAYISI', y='SERIT SAYISI',data=df)
plt.title("İki sürekli değişken arasındaki ilişki (Şerit sayısı ve  yaralı sayısı)")
plt.xlabel('YARALI SAYISI')
plt.ylabel('SERIT SAYISI')
plt.show()



plt.hist(df['AY'], bins='auto', alpha=1, color='#607c8e', rwidth=10)
plt.title('Aylara Göre Dağılım Analizi')
plt.xlabel('Değerler')
plt.ylabel('Frekans')
plt.grid(axis='y',alpha=0.75)
plt.show()

# Örnek olarak, belirli bir koşula göre segmentasyon
condition = df['ARAC MODELI'] > 2000
segmented_df = df[condition]

# Segmente edilmiş veriye göz atma
print("Segmente edilmiş veri:")
print(segmented_df.head())

plt.figure(figsize=(4, 6))
sns.countplot(x='KAZA TURU', data=df)
plt.title('Kaza türlerine göre kaza dağılımı')
plt.show()

sutun="MEVSİM"
veri_sutunu=df[sutun]

plt.figure(figsize=(4,4))
plt.pie(veri_sutunu.value_counts(), labels=veri_sutunu.value_counts().index, autopct='%1.1f%%', startangle=90)
plt.title("Mevsimlere göre kaza oranı")

plt.show()

sns.set(style="whitegrid")

plt.figure(figsize=(10,6))
sns.countplot(x='ILCE',data=df)
plt.title('Sürekli ve Kategorik Değişkenler arasındaki ilişki')
plt.show()